export enum BotHunterMode {
  BOT_DETECTION = "BOT_DETECTION",
  INVALID_FUSION_PACKET_TYPE_DETECTION = "INVALID_FUSION_PACKET_TYPE_DETECTION",
  INVALID_FUSION_PACKET_DETECTION = "INVALID_FUSION_PACKET_DETECTION",
}

export const Params = {
  MODE: BotHunterMode.INVALID_FUSION_PACKET_TYPE_DETECTION as BotHunterMode,
  INVALID_FUSION_PACKET_THRESHOLD: 10,
  INVALID_FUSION_PACKET_LIMIT_USERS: 0,
  INVALID_FUSION_PACKET_SHELL_COMMAND: "echo 'your command goes here...' ",
  MAX_PACKETS_PER_SOCKET: 40,
  CLIENT_IP_TIMEOUT_SECS: 180,
  CLIENT_PORT_TIMEOUT_SECS: 180,
  DUPLICATE_REPORT_INTERVAL_SECS: 60,
  PACKET_SOURCE: null as string | null,
  AUTOKICK: false,
  BOT_HUNTER_PROXY: null as string | null,
  REGISTRY_PROXY: null as string | null,
  SEQUENCE_ANALYSIS: true,
  RATIO_ANALYSIS: true,
  ANALYSE_RATIOS_SENSITIVITY: 0.1,
  MIN_INTERLEAVE_TRANSITIONS: 2,
  MIN_ANALYSIS_PACKETS_PER_SOCKET: 10,
  ANALYSIS_THREADS: 1,
  PCAP_FILTER: "",
  STATS_INTERVAL_SECONDS: 30,
};
